const names = require('./04-names')
const sayHello = require('./05-utils')
const data = require('./06-alternative-flavor')
require('./07-mind-grenade')
sayHello('susan')
sayHello(names.name1)
sayHello(names.name2)
console.log(data)